variable region {}
variable access_key {}
variable secret_key {}
variable lambda_function_name {}
variable lambda_description {}
variable lambda_handler {}
variable lambda_runtime {}
variable lambda_source_path {}
variable kinesis_stream {}
variable kinesis_shard_count {}
variable kinesis_retention_period {}
variable dynamodb_table_name {}
variable dynamodb_table_hash_key {}
variable dynamodb_table_hash_key_type {}
